FROM w251/keras:dev-tx2-4.3_b132

RUN apt-get update && apt-get install -y python-opencv python3-opencv

RUN pip3 install --upgrade imutils

RUN apt-get install -y build-essential cmake libgtk-3-dev libboost-all-dev

#RUN pip3 uninstall -y enum34

# RUN apt-get install -y libatlas-base-dev gfortran

# RUN  apt-get install -y build-essential python3-dev cython3 python3-setuptools python3-pip python3-wheel python3-numpy python3-pytest python3-blosc python3-brotli python3-snappy python3-lz4 libz-dev libblosc-dev liblzma-dev liblz4-dev libzstd-dev libpng-dev libwebp-dev libbz2-dev libopenjp2-7-dev libjpeg-turbo8-dev libjxr-dev liblcms2-dev libcharls-dev libaec-dev libbrotli-dev libsnappy-dev libzopfli-dev libgif-dev libtiff-dev

RUN apt-get install -y liblapack-dev gfortran

RUN apt-get install -y python3-pip
RUN pip3 install -U pip
RUN pip3 install Cython numpy

#RUN pip3 install -U scipy
RUN wget https://github.com/scipy/scipy/releases/download/v1.3.3/scipy-1.3.3.tar.gz
RUN tar -xzvf scipy-1.3.3.tar.gz scipy-1.3.3
WORKDIR scipy-1.3.3/
RUN python3 setup.py install --user 


#RUN pip3 install dlib

#WORKDIR /notebooks
#RUN wget https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz
#RUN tar -xzvf tiff-4.1.0.tar.gz
#WORKDIR tiff-4.1.0/
#RUN ./configure
#RUN make
#RUN sudo make install
#
#WORKDIR /notebooks
#RUN git clone https://github.com/uclouvain/openjpeg.git
#WORKDIR openjpeg/
#RUN mkdir build
#WORKDIR build/
#RUN cmake .. -DCMAKE_BUILD_TYPE=Release
#RUN make
#RUN sudo make install
#RUN sudo make clean
#
#
#RUN apt-get install -y python3-sklearn
#RUN apt-get install -y libaec-dev libblosc-dev libffi-dev libbrotli-dev libboost-all-dev libbz2-dev
#RUN apt-get install -y libgif-dev libopenjp2-7-dev liblcms2-dev libjpeg-dev libjxr-dev liblz4-dev liblzma-dev libpng-dev libsnappy-dev libwebp-dev libzopfli-dev libzstd-dev
#
##RUN apt-get install -y build-essential python3-dev cython3 python3-setuptools python3-pip python3-wheel python3-numpy python3-pytest python3-blosc python3-brotli python3-snappy python3-lz4 libz-dev libblosc-dev liblzma-dev liblz4-dev libzstd-dev libpng-dev libwebp-dev libbz2-dev libopenjp2-7-dev libjpeg-turbo8-dev libjxr-dev liblcms2-dev libcharls-dev libaec-dev libbrotli-dev libsnappy-dev libzopfli-dev libgif-dev libtiff-dev
#
#RUN pip3 install imagecodecs
#RUN pip3 install scikit-image 
#
RUN pip3 install -U dlib

# RUN pip3 install mtcnn

WORKDIR /
RUN mkdir -p notebooks
WORKDIR /notebooks

EXPOSE 8888

# Jupyter
CMD jupyter notebook  --no-browser --ip=0.0.0.0 --allow-root

